/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project */
        get: operations["read_project_api_project_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/algorithm-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Algorithm Overview */
        get: operations["read_algorithm_overview_api_algorithm_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Runs */
        get: operations["read_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run */
        get: operations["read_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run Draft */
        get: operations["read_run_draft_api_runs__run_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run Targets */
        get: operations["read_run_targets_api_runs__run_id__targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run Timeline */
        get: operations["read_run_timeline_api_runs__run_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run Candidates */
        get: operations["read_run_candidates_api_runs__run_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run Constraints */
        get: operations["read_run_constraints_api_runs__run_id__constraints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export-estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run Export Estimate */
        get: operations["read_run_export_estimate_api_runs__run_id__export_estimate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run Artifacts */
        get: operations["read_run_artifacts_api_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Artifact */
        get: operations["read_artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Default Workspace */
        get: operations["read_default_workspace_api_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Workspace For Run */
        get: operations["read_workspace_for_run_api_runs__run_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/design-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Design Run */
        post: operations["create_design_run_api_agent_design_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveModelInfo */
        ActiveModelInfo: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "fallback";
            /**
             * Source
             * @enum {string}
             */
            source: "best-experiment" | "runtime-fallback";
            /** Label */
            label: string;
            /** Experimentid */
            experimentId?: string | null;
            /** Checkpointfile */
            checkpointFile?: string | null;
            /** Checkpointpath */
            checkpointPath?: string | null;
            /** Checkpointmetricname */
            checkpointMetricName?: string | null;
            /** Checkpointmetricvalue */
            checkpointMetricValue?: number | null;
            /** Meanbestdeltae */
            meanBestDeltaE?: number | null;
            /** Updatedat */
            updatedAt?: string | null;
            /** Summary */
            summary: string;
        };
        /** AgentConfigurationSummary */
        AgentConfigurationSummary: {
            /** Enabled */
            enabled: boolean;
            /** Configured */
            configured: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "fallback" | "disabled";
            /** Providerlabel */
            providerLabel: string;
            /** Model */
            model: string;
            /** Apibaseurl */
            apiBaseUrl: string;
            /** Summary */
            summary: string;
        };
        /** AlgorithmExperiment */
        AlgorithmExperiment: {
            /** Id */
            id: string;
            /** Updatedat */
            updatedAt: string;
            /** Stage */
            stage: string;
            /**
             * Stagestate
             * @default unknown
             * @enum {string}
             */
            stageState: "pass" | "warning" | "fail" | "unknown";
            /** Epochs */
            epochs?: number | null;
            /** Regressorepochs */
            regressorEpochs?: number | null;
            /** Batchsize */
            batchSize?: number | null;
            /** Samplecount */
            sampleCount?: number | null;
            /**
             * Device
             * @default unknown
             */
            device: string;
            /** Devicename */
            deviceName?: string | null;
            /**
             * Checkpointready
             * @default false
             */
            checkpointReady: boolean;
            /**
             * Losshistoryready
             * @default false
             */
            lossHistoryReady: boolean;
            /**
             * Metricsready
             * @default false
             */
            metricsReady: boolean;
            /** Meanbestdeltae */
            meanBestDeltaE?: number | null;
            /** Papertargetmeanbestdeltae */
            paperTargetMeanBestDeltaE?: number | null;
            /** D2Within5Nmratio */
            d2Within5nmRatio?: number | null;
            /** Papertargetd2Within5Nmratio */
            paperTargetD2Within5nmRatio?: number | null;
            /** Averageretrievaldeltae */
            averageRetrievalDeltaE?: number | null;
            /** Averagecgandeltae */
            averageCganDeltaE?: number | null;
            /**
             * Cganbeatsretrievalcount
             * @default 0
             */
            cganBeatsRetrievalCount: number;
            /**
             * Totaltargetscompared
             * @default 0
             */
            totalTargetsCompared: number;
            /** Summary */
            summary: string;
        };
        /** AlgorithmHeadlineMetric */
        AlgorithmHeadlineMetric: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Detail */
            detail: string;
            /**
             * State
             * @default unknown
             * @enum {string}
             */
            state: "pass" | "warning" | "fail" | "unknown";
        };
        /** AlgorithmOperationStep */
        AlgorithmOperationStep: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Command */
            command?: string | null;
            /** Expectedresult */
            expectedResult?: string | null;
        };
        /** AlgorithmOverview */
        AlgorithmOverview: {
            /** Algorithmname */
            algorithmName: string;
            /** Businessgoal */
            businessGoal: string;
            /** Workflowsummary */
            workflowSummary: string;
            /** Plainexplanation */
            plainExplanation: string;
            /** Currentassessment */
            currentAssessment: string;
            /** Trainingconclusion */
            trainingConclusion: string;
            /** Gputrainingsummary */
            gpuTrainingSummary: string;
            /** Currentenvironmentsummary */
            currentEnvironmentSummary: string;
            /** Artifactrootpath */
            artifactRootPath: string;
            /** Guidedocumentpath */
            guideDocumentPath: string;
            /** Bestexperimentid */
            bestExperimentId?: string | null;
            /** Latestexperimentid */
            latestExperimentId?: string | null;
            bestExperiment?: components["schemas"]["AlgorithmExperiment"] | null;
            latestExperiment?: components["schemas"]["AlgorithmExperiment"] | null;
            activeModel?: components["schemas"]["ActiveModelInfo"] | null;
            agentConfiguration?: components["schemas"]["AgentConfigurationSummary"] | null;
            /** Experiments */
            experiments: components["schemas"]["AlgorithmExperiment"][];
            /** Headlinemetrics */
            headlineMetrics: components["schemas"]["AlgorithmHeadlineMetric"][];
            /** Targetcomparisons */
            targetComparisons: components["schemas"]["AlgorithmTargetComparison"][];
            /** Operationsteps */
            operationSteps: components["schemas"]["AlgorithmOperationStep"][];
        };
        /** AlgorithmTargetComparison */
        AlgorithmTargetComparison: {
            /** Targethex */
            targetHex: string;
            /** Retrievaldeltae */
            retrievalDeltaE: number;
            /** Cgandeltae */
            cganDeltaE: number;
            /**
             * Winner
             * @enum {string}
             */
            winner: "retrieval" | "cgan" | "tie";
        };
        /** ApiErrorPayload */
        ApiErrorPayload: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ArtifactDetail */
        ArtifactDetail: {
            /** Id */
            id: string;
            /** Runid */
            runId: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "report" | "preview" | "export";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "running" | "pending";
            /** Description */
            description: string;
            /** Metadata */
            metadata: components["schemas"]["ArtifactMetadataItem"][];
        };
        /** ArtifactMetadataItem */
        ArtifactMetadataItem: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** ArtifactSummary */
        ArtifactSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "report" | "preview" | "export";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "running" | "pending";
        };
        /** CandidateMetric */
        CandidateMetric: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** CandidateParameter */
        CandidateParameter: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** CandidateSolution */
        CandidateSolution: {
            /** Id */
            id: string;
            /** Rank */
            rank: number;
            /** Group */
            group: string;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "Recommended" | "Robust" | "Watch" | "Blocked";
            /** Parameters */
            parameters: components["schemas"]["CandidateParameter"][];
            /** Metrics */
            metrics: components["schemas"]["CandidateMetric"][];
            /** Targetcolorhex */
            targetColorHex: string;
            /** Simulatedcolorhex */
            simulatedColorHex: string;
            /** Processpluscolorhex */
            processPlusColorHex: string;
            /** Processminuscolorhex */
            processMinusColorHex: string;
            /** Rationale */
            rationale: string;
        };
        /** ConstraintCheck */
        ConstraintCheck: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /**
             * State
             * @enum {string}
             */
            state: "pass" | "warning" | "fail" | "unknown";
        };
        /** DecisionSupport */
        DecisionSupport: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "heuristic" | "llm";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Recommendedcandidateid */
            recommendedCandidateId?: string | null;
            /** Nextaction */
            nextAction: string;
            /** Rationale */
            rationale: string[];
            /** Risks */
            risks: string[];
        };
        /** DesignRequest */
        DesignRequest: {
            /** Requirementtext */
            requirementText: string;
            /** Targethex */
            targetHex: string;
            /**
             * Topk
             * @default 3
             */
            topK: number;
            /**
             * Thetadeg
             * @default 0
             */
            thetaDeg: number;
            /**
             * Polarization
             * @default unpolarized
             * @enum {string}
             */
            polarization: "te" | "tm" | "unpolarized";
            /**
             * Designmode
             * @default structural-color
             * @enum {string}
             */
            designMode: "structural-color" | "neural-holography";
        };
        /** DesignRunResponse */
        DesignRunResponse: {
            activeRun: components["schemas"]["RunSummary"];
            draft: components["schemas"]["WorkspaceDraft"];
            /** Targets */
            targets: components["schemas"]["TargetAsset"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEvent"][];
            /** Candidates */
            candidates: components["schemas"]["CandidateSolution"][];
            /** Constraints */
            constraints: components["schemas"]["ConstraintCheck"][];
            exportEstimate: components["schemas"]["ExportEstimate"];
            activeModel: components["schemas"]["ActiveModelInfo"];
            agentConfiguration: components["schemas"]["AgentConfigurationSummary"];
            decisionSupport: components["schemas"]["DecisionSupport"];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown | null;
        };
        /** ExportEstimate */
        ExportEstimate: {
            /** Dimensions */
            dimensions: string;
            /** Filesize */
            fileSize: string;
            /** Tileplan */
            tilePlan: string;
            /** Format */
            format: string;
            /** Progress */
            progress: number;
            /** Tileprogress */
            tileProgress: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Draft" | "Validating" | "Simulating" | "Ranking" | "Needs approval" | "Exporting" | "Complete" | "Failed";
            /** Updatedat */
            updatedAt: string;
            /**
             * Warning
             * @default false
             */
            warning: boolean;
        };
        /** TargetAsset */
        TargetAsset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "color" | "image" | "multi-view";
            /** Detail */
            detail: string;
            /** Swatchhex */
            swatchHex?: string | null;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "agent" | "tool" | "warning" | "approval" | "result";
            /** Label */
            label: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Meta */
            meta?: string | null;
            /** Status */
            status?: ("Draft" | "Validating" | "Simulating" | "Ranking" | "Needs approval" | "Exporting" | "Complete" | "Failed") | "Running" | null;
            /** Actionlabel */
            actionLabel?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceDetail */
        WorkspaceDetail: {
            project: components["schemas"]["WorkspaceProject"];
            activeRun: components["schemas"]["RunSummary"];
            draft: components["schemas"]["WorkspaceDraft"];
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            /** Targets */
            targets: components["schemas"]["TargetAsset"][];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactSummary"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEvent"][];
            /** Candidates */
            candidates: components["schemas"]["CandidateSolution"][];
            /** Constraints */
            constraints: components["schemas"]["ConstraintCheck"][];
            exportEstimate: components["schemas"]["ExportEstimate"];
            activeModel: components["schemas"]["ActiveModelInfo"];
            agentConfiguration: components["schemas"]["AgentConfigurationSummary"];
            decisionSupport: components["schemas"]["DecisionSupport"];
        };
        /** WorkspaceDraft */
        WorkspaceDraft: {
            /** Requirementtext */
            requirementText: string;
            /**
             * Designmode
             * @default structural-color
             */
            designMode: string;
            /**
             * Referencesource
             * @default 10.1515_nanoph-2022-0095.pdf
             */
            referenceSource: string;
            /**
             * Outputkind
             * @default Thin-film candidate set
             */
            outputKind: string;
            /** Targetlabel */
            targetLabel: string;
            /** Targetvalue */
            targetValue: string;
            /** Incidenceanglelabel */
            incidenceAngleLabel: string;
            /** Incidenceanglevalue */
            incidenceAngleValue: string;
            /** Polarizationlabel */
            polarizationLabel: string;
            /** Polarizationvalue */
            polarizationValue: string;
            /** Heightwindow */
            heightWindow: string;
            /** Exportmode */
            exportMode: string;
            /**
             * Calibrationmode
             * @default Forward simulation
             */
            calibrationMode: string;
            /**
             * Runtimetarget
             * @default Preview-first offline design
             */
            runtimeTarget: string;
        };
        /** WorkspaceProject */
        WorkspaceProject: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_project_api_project_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceProject"];
                };
            };
        };
    };
    read_algorithm_overview_api_algorithm_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlgorithmOverview"];
                };
            };
        };
    };
    read_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    read_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_draft_api_runs__run_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDraft"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_targets_api_runs__run_id__targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetAsset"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_timeline_api_runs__run_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEvent"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_candidates_api_runs__run_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSolution"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_constraints_api_runs__run_id__constraints_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintCheck"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_export_estimate_api_runs__run_id__export_estimate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportEstimate"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_artifacts_api_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactSummary"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_default_workspace_api_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDetail"];
                };
            };
        };
    };
    read_workspace_for_run_api_runs__run_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_design_run_api_agent_design_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
